# SPDX-License-Identifier: GPL-2.0-only


obj-$(CONFIG_IPA) += ipa_v2/ ipa_clients/ ipa_common
obj-$(CONFIG_IPA3) += ipa_v3/ ipa_clients/ ipa_common
obj-$(CONFIG_IPA_UT) += test/


obj-$(CONFIG_IPA) += ipa_v2/ ipa_clients/ $(IPA_COMMON)
obj-$(CONFIG_IPA3) += ipa_v3/ ipa_clients/ $(IPA_COMMON)
obj-$(CONFIG_IPA_UT) += test/
